apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: webapp-container
        image: backend_java-webapp:latest
        ports:
        - containerPort: 80  # Port your application listens on
